import { TILE_SIZE } from '../playerConfig';
import type { UpgradeDefinition, UpgradeId } from '../types';

export const SKILL_TREE_IDS: UpgradeId[] = [
  'prospector_core',
  'spring_boots', 'micro_jetpack', 'rocket_pants',
  'wide_visor', 'ore_scanner', 'xray_potato',
  'laser_focus', 'chain_lightning', 'storm_subscription',
  'cargo_tetris', 'pocket_wormhole', 'rubber_duck_protocol',
];

export const UPGRADE_DEFINITIONS: Record<UpgradeId, UpgradeDefinition> = {
  prospector_core: {
    id: 'prospector_core', label: 'Prospektor-Kern', description: 'Schaltet die vier Forschungsäste frei und spendiert 10 Energie.', category: 'core',
    cost: { credits: 50 }, effects: [{ stat: 'maxEnergy', op: 'add', value: 10 }], tree: { x: 0, y: 0, branch: 'core' },
  },
  spring_boots: {
    id: 'spring_boots', label: 'Federstiefel', description: '12 % höher springen. Boing ist eine Wissenschaft.', category: 'boots',
    cost: { credits: 100 }, prerequisites: ['prospector_core'], effects: [{ stat: 'jumpVelocity', op: 'multiply', value: 1.12 }], tree: { x: -1, y: 1, branch: 'movement' },
  },
  micro_jetpack: {
    id: 'micro_jetpack', label: 'Mikro-Jetpack', description: 'Ein zusätzlicher Sprung in der Luft.', category: 'boots',
    cost: { credits: 350 }, prerequisites: ['spring_boots'], effects: [{ stat: 'airJumps', op: 'set', value: 1 }], tree: { x: -2, y: 2, branch: 'movement' },
  },
  rocket_pants: {
    id: 'rocket_pants', label: 'Raketenhose', description: 'Zwei Luftsprünge und 28 % weniger Schwerkraft. Garantie erloschen.', category: 'boots',
    cost: { credits: 900 }, prerequisites: ['micro_jetpack'], effects: [{ stat: 'airJumps', op: 'set', value: 2 }, { stat: 'gravityMultiplier', op: 'multiply', value: 0.72 }], tree: { x: -3, y: 3, branch: 'movement' },
  },
  wide_visor: {
    id: 'wide_visor', label: 'Weitwinkel-Visier', description: 'Erhöht die permanente Sichtweite auf 3 Tiles.', category: 'visor',
    cost: { credits: 100 }, prerequisites: ['prospector_core'], effects: [{ stat: 'sightRadius', op: 'set', value: 3 }], tree: { x: 1, y: -1, branch: 'vision' },
  },
  ore_scanner: {
    id: 'ore_scanner', label: 'Erz-Scanner', description: 'Markiert Erzadern im Radius von 4 Tiles durch den Fog.', category: 'visor',
    cost: { credits: 350 }, prerequisites: ['wide_visor'], effects: [{ stat: 'oreScannerRadius', op: 'set', value: 4 }], tree: { x: 2, y: -2, branch: 'vision' },
  },
  xray_potato: {
    id: 'xray_potato', label: 'Röntgen-Kartoffel', description: 'Scanner-Radius 7 und +1 Sicht. Fragt nicht, warum sie summt.', category: 'visor',
    cost: { credits: 900 }, prerequisites: ['ore_scanner'], effects: [{ stat: 'oreScannerRadius', op: 'set', value: 7 }, { stat: 'sightRadius', op: 'add', value: 1 }], tree: { x: 3, y: -3, branch: 'vision' },
  },
  laser_focus: {
    id: 'laser_focus', label: 'Laser-Fokus', description: '25 % mehr Mining-Schaden.', category: 'laser',
    cost: { credits: 125 }, prerequisites: ['prospector_core'], effects: [{ stat: 'miningDamagePerSec', op: 'multiply', value: 1.25 }], tree: { x: 1, y: 1, branch: 'mining' },
  },
  chain_lightning: {
    id: 'chain_lightning', label: 'Kettenblitz', description: 'Jeder zerstörte Block zerlegt zwei benachbarte Blöcke.', category: 'laser',
    cost: { credits: 450 }, prerequisites: ['laser_focus'], effects: [{ stat: 'chainMiningTargets', op: 'set', value: 2 }], tree: { x: 2, y: 2, branch: 'mining' },
  },
  storm_subscription: {
    id: 'storm_subscription', label: 'Gewitter-Abo', description: 'Vier Kettenziele und 15 % mehr Schaden. Monatlich kündbar.*', category: 'laser',
    cost: { credits: 1100 }, prerequisites: ['chain_lightning'], effects: [{ stat: 'chainMiningTargets', op: 'set', value: 4 }, { stat: 'miningDamagePerSec', op: 'multiply', value: 1.15 }], tree: { x: 3, y: 3, branch: 'mining' },
  },
  cargo_tetris: {
    id: 'cargo_tetris', label: 'Cargo-Tetris', description: '+1 Cargo-Slot. Reihen verschwinden leider nicht.', category: 'cargo',
    cost: { credits: 100 }, prerequisites: ['prospector_core'], effects: [{ stat: 'cargoSlots', op: 'add', value: 1 }], tree: { x: -1, y: -1, branch: 'utility' },
  },
  pocket_wormhole: {
    id: 'pocket_wormhole', label: 'Taschen-Wurmloch', description: '+3 Stackgröße und 140 Pixel Sammelradius.', category: 'cargo',
    cost: { credits: 400 }, prerequisites: ['cargo_tetris'], effects: [{ stat: 'cargoStackLimit', op: 'add', value: 3 }, { stat: 'pickupRadius', op: 'set', value: 140 }], tree: { x: -2, y: -2, branch: 'utility' },
  },
  rubber_duck_protocol: {
    id: 'rubber_duck_protocol', label: 'Goldene Gummiente', description: '+25 Leben, 220 Pixel Magnet und 15 % weniger Schwerkraft. Quak.', category: 'core',
    cost: { credits: 1000 }, prerequisites: ['pocket_wormhole'], effects: [{ stat: 'maxHealth', op: 'add', value: 25 }, { stat: 'pickupRadius', op: 'set', value: 220 }, { stat: 'gravityMultiplier', op: 'multiply', value: 0.85 }], tree: { x: -3, y: -3, branch: 'utility' },
  },
  laser_mk2: {
    id: 'laser_mk2',
    label: 'Laser MK2',
    category: 'laser',
    cost: { credits: 100 },
    effects: [{ stat: 'miningRange', op: 'add', value: TILE_SIZE }],
  },
  laser_mk3: {
    id: 'laser_mk3',
    label: 'Laser MK3',
    category: 'laser',
    cost: { credits: 300 },
    prerequisites: ['laser_mk2'],
    effects: [{ stat: 'miningRange', op: 'add', value: TILE_SIZE * 2 }],
  },
  laser_mk4: {
    id: 'laser_mk4',
    label: 'Laser MK4',
    category: 'laser',
    cost: { credits: 800 },
    prerequisites: ['laser_mk3'],
    effects: [{ stat: 'miningRange', op: 'add', value: TILE_SIZE * 3 }],
  },
  piercing_laser: {
    id: 'piercing_laser',
    label: 'Durchschlags-Laser',
    category: 'laser',
    cost: { credits: 500 },
    effects: [{ stat: 'miningDamagePerSec', op: 'multiply', value: 1.15 }],
  },
  fast_laser: {
    id: 'fast_laser',
    label: 'Schnell-Laser',
    category: 'laser',
    cost: { credits: 600 },
    effects: [{ stat: 'miningDamagePerSec', op: 'multiply', value: 1.5 }],
  },
  auto_laser: {
    id: 'auto_laser',
    label: 'Auto-Laser',
    category: 'laser',
    cost: { credits: 1000 },
    effects: [{ stat: 'energyCostPerSec', op: 'multiply', value: 0.9 }],
  },
  spectral_laser: {
    id: 'spectral_laser',
    label: 'Spektral-Laser',
    category: 'laser',
    cost: { credits: 1500 },
    effects: [{ stat: 'sightRadius', op: 'add', value: 1 }],
  },
  visor_mk1: {
    id: 'visor_mk1',
    label: 'Visier MK1',
    category: 'visor',
    cost: { credits: 150 },
    effects: [{ stat: 'sightRadius', op: 'set', value: 3 }],
  },
  visor_mk2: {
    id: 'visor_mk2',
    label: 'Visier MK2',
    category: 'visor',
    cost: { credits: 400 },
    prerequisites: ['visor_mk1'],
    effects: [{ stat: 'sightRadius', op: 'set', value: 4 }],
  },
  radar_visor: {
    id: 'radar_visor',
    label: 'Radar-Visier',
    category: 'visor',
    cost: { credits: 900 },
    prerequisites: ['visor_mk2'],
    effects: [{ stat: 'sightRadius', op: 'set', value: 5 }],
  },
  quantum_visor: {
    id: 'quantum_visor',
    label: 'Quantum-Visier',
    category: 'visor',
    cost: { credits: 2000 },
    prerequisites: ['radar_visor'],
    effects: [{ stat: 'sightRadius', op: 'set', value: 6 }],
  },
  battery_mk1: {
    id: 'battery_mk1',
    label: 'Batterie MK1',
    category: 'battery',
    cost: { credits: 400 },
    effects: [{ stat: 'maxEnergy', op: 'set', value: 150 }],
  },
  battery_mk2: {
    id: 'battery_mk2',
    label: 'Batterie MK2',
    category: 'battery',
    cost: { credits: 900 },
    prerequisites: ['battery_mk1'],
    effects: [{ stat: 'maxEnergy', op: 'set', value: 250 }],
  },
  battery_mk3: {
    id: 'battery_mk3',
    label: 'Batterie MK3',
    category: 'battery',
    cost: { credits: 2000 },
    prerequisites: ['battery_mk2'],
    effects: [{ stat: 'maxEnergy', op: 'set', value: 400 }],
  },
  battery_fusion: {
    id: 'battery_fusion',
    label: 'Batterie Fusion',
    category: 'battery',
    cost: { credits: 5000 },
    prerequisites: ['battery_mk3'],
    effects: [{ stat: 'maxEnergy', op: 'set', value: 700 }],
  },
  boots_mk1: {
    id: 'boots_mk1',
    label: 'Stiefel MK1',
    category: 'boots',
    cost: { credits: 500 },
    effects: [{ stat: 'jumpVelocity', op: 'multiply', value: 1.05 }],
  },
  boots_mk2: {
    id: 'boots_mk2',
    label: 'Stiefel MK2',
    category: 'boots',
    cost: { credits: 1200 },
    prerequisites: ['boots_mk1'],
    effects: [{ stat: 'jumpVelocity', op: 'multiply', value: 1.1 }],
  },
  boots_mk3: {
    id: 'boots_mk3',
    label: 'Stiefel MK3',
    category: 'boots',
    cost: { credits: 3000 },
    prerequisites: ['boots_mk2'],
    effects: [{ stat: 'jumpVelocity', op: 'multiply', value: 1.16 }],
  },
  boots_mk4: {
    id: 'boots_mk4',
    label: 'Stiefel MK4',
    category: 'boots',
    cost: { credits: 6000 },
    prerequisites: ['boots_mk3'],
    effects: [{ stat: 'jumpVelocity', op: 'multiply', value: 1.22 }],
  },
  speed_mk1: {
    id: 'speed_mk1',
    label: 'Servo-Antrieb I',
    category: 'boots',
    cost: { credits: 60 },
    effects: [{ stat: 'moveSpeed', op: 'set', value: 489 }],
  },
  speed_mk2: {
    id: 'speed_mk2',
    label: 'Servo-Antrieb II',
    category: 'boots',
    cost: { credits: 180 },
    prerequisites: ['speed_mk1'],
    effects: [{ stat: 'moveSpeed', op: 'set', value: 508 }],
  },
  speed_mk3: {
    id: 'speed_mk3',
    label: 'Servo-Antrieb III',
    category: 'boots',
    cost: { credits: 420 },
    prerequisites: ['speed_mk2'],
    effects: [{ stat: 'moveSpeed', op: 'set', value: 526 }],
  },
  core_compass: {
    id: 'core_compass',
    label: 'Core-Compass',
    category: 'core',
    cost: { credits: 800 },
    effects: [],
  },
  core_scanner: {
    id: 'core_scanner',
    label: 'Core-Scanner',
    category: 'core',
    cost: { credits: 2000 },
    prerequisites: ['core_compass'],
    effects: [],
  },
  advanced_mapper: {
    id: 'advanced_mapper',
    label: 'Advanced-Mapper',
    category: 'core',
    cost: { credits: 5000 },
    prerequisites: ['core_scanner'],
    effects: [{ stat: 'sightRadius', op: 'add', value: 1 }],
  },
  cargo_mk1: {
    id: 'cargo_mk1',
    label: 'Erweiterter Laderaum I',
    category: 'cargo',
    cost: { credits: 75 },
    effects: [{ stat: 'cargoSlots', op: 'set', value: 3 }],
  },
  cargo_mk2: {
    id: 'cargo_mk2',
    label: 'Erweiterter Laderaum II',
    category: 'cargo',
    cost: { credits: 225 },
    prerequisites: ['cargo_mk1'],
    effects: [{ stat: 'cargoSlots', op: 'set', value: 4 }],
  },
  cargo_mk3: {
    id: 'cargo_mk3',
    label: 'Erweiterter Laderaum III',
    category: 'cargo',
    cost: { credits: 525 },
    prerequisites: ['cargo_mk2'],
    effects: [{ stat: 'cargoSlots', op: 'set', value: 5 }],
  },
  cargo_stack_mk1: {
    id: 'cargo_stack_mk1',
    label: 'Cargo-Slot-Größe I',
    category: 'cargo',
    cost: { credits: 90 },
    effects: [{ stat: 'cargoStackLimit', op: 'set', value: 5 }],
  },
  cargo_stack_mk2: {
    id: 'cargo_stack_mk2',
    label: 'Cargo-Slot-Größe II',
    category: 'cargo',
    cost: { credits: 260 },
    prerequisites: ['cargo_stack_mk1'],
    effects: [{ stat: 'cargoStackLimit', op: 'set', value: 8 }],
  },
  cargo_stack_mk3: {
    id: 'cargo_stack_mk3',
    label: 'Cargo-Slot-Größe III',
    category: 'cargo',
    cost: { credits: 600 },
    prerequisites: ['cargo_stack_mk2'],
    effects: [{ stat: 'cargoStackLimit', op: 'set', value: 12 }],
  },
  engine_mk1: {
    id: 'engine_mk1',
    label: 'Triebwerke MK1',
    category: 'ship',
    cost: { credits: 500 },
    effects: [{ stat: 'fuelEfficiency', op: 'multiply', value: 1.1 }],
  },
  engine_mk2: {
    id: 'engine_mk2',
    label: 'Triebwerke MK2',
    category: 'ship',
    cost: { credits: 1500 },
    prerequisites: ['engine_mk1'],
    effects: [{ stat: 'fuelEfficiency', op: 'multiply', value: 1.25 }],
  },
  engine_mk3: {
    id: 'engine_mk3',
    label: 'Triebwerke MK3',
    category: 'ship',
    cost: { credits: 4000 },
    prerequisites: ['engine_mk2'],
    effects: [{ stat: 'fuelEfficiency', op: 'multiply', value: 1.4 }],
  },
};
