import type { FontAssetDefinition } from '@gravity-dig/game-core';

// Auto-generated by apps/game/scripts/build-font-assets.mjs.
// Add font files to apps/game/public/fonts and rerun the build/dev script.
export const GENERATED_FONT_ASSETS = [
  {
    "key": "silkscreen-latin-700",
    "family": "Silkscreen",
    "label": "Silkscreen Bold",
    "path": "/fonts/silkscreen-latin-700.woff2",
    "weight": "700"
  }
] satisfies readonly FontAssetDefinition[];
