import { TILE_SIZE } from '../../config/gameConfig';
import type { UpgradeDefinition, UpgradeId } from '../types';

export const UPGRADE_DEFINITIONS: Record<UpgradeId, UpgradeDefinition> = {
  laser_mk2: {
    id: 'laser_mk2',
    label: 'Laser MK2',
    category: 'laser',
    cost: { credits: 100 },
    effects: [{ stat: 'miningRange', op: 'add', value: TILE_SIZE }],
  },
  laser_mk3: {
    id: 'laser_mk3',
    label: 'Laser MK3',
    category: 'laser',
    cost: { credits: 300 },
    prerequisites: ['laser_mk2'],
    effects: [{ stat: 'miningRange', op: 'add', value: TILE_SIZE * 2 }],
  },
  laser_mk4: {
    id: 'laser_mk4',
    label: 'Laser MK4',
    category: 'laser',
    cost: { credits: 800 },
    prerequisites: ['laser_mk3'],
    effects: [{ stat: 'miningRange', op: 'add', value: TILE_SIZE * 3 }],
  },
  piercing_laser: {
    id: 'piercing_laser',
    label: 'Durchschlags-Laser',
    category: 'laser',
    cost: { credits: 500 },
    effects: [{ stat: 'miningDamagePerSec', op: 'multiply', value: 1.15 }],
  },
  fast_laser: {
    id: 'fast_laser',
    label: 'Schnell-Laser',
    category: 'laser',
    cost: { credits: 600 },
    effects: [{ stat: 'miningDamagePerSec', op: 'multiply', value: 1.5 }],
  },
  auto_laser: {
    id: 'auto_laser',
    label: 'Auto-Laser',
    category: 'laser',
    cost: { credits: 1000 },
    effects: [{ stat: 'energyCostPerSec', op: 'multiply', value: 0.9 }],
  },
  spectral_laser: {
    id: 'spectral_laser',
    label: 'Spektral-Laser',
    category: 'laser',
    cost: { credits: 1500 },
    effects: [{ stat: 'sightRadius', op: 'add', value: 1 }],
  },
  visor_mk1: {
    id: 'visor_mk1',
    label: 'Visier MK1',
    category: 'visor',
    cost: { credits: 150 },
    effects: [{ stat: 'sightRadius', op: 'set', value: 4 }],
  },
  visor_mk2: {
    id: 'visor_mk2',
    label: 'Visier MK2',
    category: 'visor',
    cost: { credits: 400 },
    prerequisites: ['visor_mk1'],
    effects: [{ stat: 'sightRadius', op: 'set', value: 5 }],
  },
  radar_visor: {
    id: 'radar_visor',
    label: 'Radar-Visier',
    category: 'visor',
    cost: { credits: 900 },
    prerequisites: ['visor_mk2'],
    effects: [{ stat: 'sightRadius', op: 'set', value: 6 }],
  },
  quantum_visor: {
    id: 'quantum_visor',
    label: 'Quantum-Visier',
    category: 'visor',
    cost: { credits: 2000 },
    prerequisites: ['radar_visor'],
    effects: [{ stat: 'sightRadius', op: 'set', value: 7 }],
  },
  battery_mk1: {
    id: 'battery_mk1',
    label: 'Batterie MK1',
    category: 'battery',
    cost: { credits: 400 },
    effects: [{ stat: 'maxEnergy', op: 'set', value: 150 }],
  },
  battery_mk2: {
    id: 'battery_mk2',
    label: 'Batterie MK2',
    category: 'battery',
    cost: { credits: 900 },
    prerequisites: ['battery_mk1'],
    effects: [{ stat: 'maxEnergy', op: 'set', value: 250 }],
  },
  battery_mk3: {
    id: 'battery_mk3',
    label: 'Batterie MK3',
    category: 'battery',
    cost: { credits: 2000 },
    prerequisites: ['battery_mk2'],
    effects: [{ stat: 'maxEnergy', op: 'set', value: 400 }],
  },
  battery_fusion: {
    id: 'battery_fusion',
    label: 'Batterie Fusion',
    category: 'battery',
    cost: { credits: 5000 },
    prerequisites: ['battery_mk3'],
    effects: [{ stat: 'maxEnergy', op: 'set', value: 700 }],
  },
  boots_mk1: {
    id: 'boots_mk1',
    label: 'Stiefel MK1',
    category: 'boots',
    cost: { credits: 500 },
    effects: [{ stat: 'jumpVelocity', op: 'multiply', value: 1.05 }],
  },
  boots_mk2: {
    id: 'boots_mk2',
    label: 'Stiefel MK2',
    category: 'boots',
    cost: { credits: 1200 },
    prerequisites: ['boots_mk1'],
    effects: [{ stat: 'jumpVelocity', op: 'multiply', value: 1.1 }],
  },
  boots_mk3: {
    id: 'boots_mk3',
    label: 'Stiefel MK3',
    category: 'boots',
    cost: { credits: 3000 },
    prerequisites: ['boots_mk2'],
    effects: [{ stat: 'jumpVelocity', op: 'multiply', value: 1.16 }],
  },
  boots_mk4: {
    id: 'boots_mk4',
    label: 'Stiefel MK4',
    category: 'boots',
    cost: { credits: 6000 },
    prerequisites: ['boots_mk3'],
    effects: [{ stat: 'jumpVelocity', op: 'multiply', value: 1.22 }],
  },
  core_compass: {
    id: 'core_compass',
    label: 'Core-Compass',
    category: 'core',
    cost: { credits: 800 },
    effects: [],
  },
  core_scanner: {
    id: 'core_scanner',
    label: 'Core-Scanner',
    category: 'core',
    cost: { credits: 2000 },
    prerequisites: ['core_compass'],
    effects: [],
  },
  advanced_mapper: {
    id: 'advanced_mapper',
    label: 'Advanced-Mapper',
    category: 'core',
    cost: { credits: 5000 },
    prerequisites: ['core_scanner'],
    effects: [{ stat: 'sightRadius', op: 'add', value: 1 }],
  },
  cargo_mk1: {
    id: 'cargo_mk1',
    label: 'Erweiterter Laderaum I',
    category: 'cargo',
    cost: { credits: 300 },
    effects: [{ stat: 'cargoCapacity', op: 'set', value: 150 }],
  },
  cargo_mk2: {
    id: 'cargo_mk2',
    label: 'Erweiterter Laderaum II',
    category: 'cargo',
    cost: { credits: 800 },
    prerequisites: ['cargo_mk1'],
    effects: [{ stat: 'cargoCapacity', op: 'set', value: 200 }],
  },
  cargo_mk3: {
    id: 'cargo_mk3',
    label: 'Erweiterter Laderaum III',
    category: 'cargo',
    cost: { credits: 2000 },
    prerequisites: ['cargo_mk2'],
    effects: [{ stat: 'cargoCapacity', op: 'set', value: 300 }],
  },
  engine_mk1: {
    id: 'engine_mk1',
    label: 'Triebwerke MK1',
    category: 'ship',
    cost: { credits: 500 },
    effects: [{ stat: 'fuelEfficiency', op: 'multiply', value: 1.1 }],
  },
  engine_mk2: {
    id: 'engine_mk2',
    label: 'Triebwerke MK2',
    category: 'ship',
    cost: { credits: 1500 },
    prerequisites: ['engine_mk1'],
    effects: [{ stat: 'fuelEfficiency', op: 'multiply', value: 1.25 }],
  },
  engine_mk3: {
    id: 'engine_mk3',
    label: 'Triebwerke MK3',
    category: 'ship',
    cost: { credits: 4000 },
    prerequisites: ['engine_mk2'],
    effects: [{ stat: 'fuelEfficiency', op: 'multiply', value: 1.4 }],
  },
};
